language: python
python:
  - "3.5"
install:
    - pip install -r requirements.txt
    - npm install jshint
before_script:
    - flake8 .
    - jshint ostp_files_emberV2/
script:
    - python backend/manage.py test api