language: python
python:
  - "3.5"
install:
    - pip install -r requirements.txt
    - npm install jshint
before_script:
    - flake8 backend/
    - jshint frontend/
script:
    - python backend/manage.py test api
