local:
   CLIENT_ID: 83a3354d3b0f41a9a1e3df1e08ac7ed1
   PERSONAL_ACCESS_TOKEN: bBggLSya8t3loP8GPbLX6DjjGmyp8kuyEvsHhgkF
   OAUTH_SCOPES: osf.full_read osf.full_write
   REDIRECT_URI: http://localhost:4200/

stage:
    CLIENT_ID: 3df077f151dd4de48876baf63fa9d7a6
    PERSONAL_ACCESS_TOKEN: NL83YVL8EZMyKUFpbA4vrYsdt9ET0tqmZZtDP6uh
    OAUTH_SCOPES: osf.full_read osf.full_write
    REDIRECT_URI: http://staging-grants.osf.io:4200/

######## ember-osf settings ########
# local:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

# stage:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

# stage2:
#    CLIENT_ID: null
#    PERSONAL_ACCESS_TOKEN: null
#    OAUTH_SCOPES: osf.full_read osf.full_write
#    REDIRECT_URI: http://localhost:4200/login/

# test:
#     CLIENT_ID: null
#     PERSONAL_ACCESS_TOKEN: null
#     OAUTH_SCOPES: osf.full_read osf.full_write
#     REDIRECT_URI: http://localhost:4200/
######### end ember-osf ##########
